import styles from "../../styles/Upcoming.module.scss";
import { createPortal } from "react-dom";
import { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import Modal from "../../src/components/Modal";
import Head from "next/head";
import LogoBar from "../../src/components/LogoBar";
import NavMenu from "../../src/components/NavMenu";
import "react-modern-drawer/dist/index.css";
import UpcomingMovieCard from "../../src/components/UpcomingCard";

export default function Upcoming({ movies }) {
	const [isBrowser, setIsBrowser] = useState(false); // required to access document
	const modalState = useSelector((state) => state.modal); // redux modalState

	useEffect(() => {
		setIsBrowser(true); // set to true when document is loaded/accessible
	}, []);

	// Disable background scroll when modal is visible
	if (isBrowser && modalState.isVisible) {
		const body = document.querySelector("body");
		body.style.overflow = "hidden";
	}

	// Reset disabled background scroll behavior
	if (isBrowser && !modalState.isVisible) {
		const body = document.querySelector("body");
		body.style.overflow = "";
	}

	console.log(modalState);
	const trailerModal =
		isBrowser && modalState.type === "view-trailer"
			? createPortal(
					<Modal header={`${modalState.info.title} - Trailer`} color="#007DD8">
						<iframe
							width="100%"
							height="400px"
							frameBorder="0"
							border="0"
							cellSpacing="0"
							src={`${modalState.info.trailerLink}?autoplay=1`}
						></iframe>
					</Modal>,
					document.getElementById("modal-root")
			  )
			: null;

	return (
		<div>
			<Head>
				<title>
					Woodside Cinemas | Indian Movies, Showtimes, Tickets, Trailers
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* View Trailer Modal */}
			{isBrowser &&
				modalState.isVisible &&
				modalState.type === "view-trailer" &&
				trailerModal}

			<LogoBar />
			<NavMenu />
			<main className={styles.container}>
				<div className={styles.content}>
					<h1>Upcoming Movies</h1>
					<div className={styles.box}>
						{movies.map((movie, index) => (
							<UpcomingMovieCard
								key={index}
								image={movie.posterLink}
								title={movie.title}
								trailerLink={movie.trailerLink}
							/>
						))}
					</div>
				</div>
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	try {
		const moviesResponse = await fetch(
			`${process.env.NEXT_PUBLIC_BACKEND}/movies/upcoming`
		);
		if (moviesResponse.ok) {
			const movies = await moviesResponse.json();
			return {
				props: {
					movies,
				},
			};
		}
		throw new Error();
	} catch (error) {
		console.log(error);
		return {
			props: {
				movies: [],
			},
		};
	}
}
