import styles from "../../styles/Upcoming.module.scss";
import Head from "next/head";
import LogoBar from "../../src/components/LogoBar";
import NavMenu from "../../src/components/NavMenu";
import "react-modern-drawer/dist/index.css";

export default function Upcoming() {
	return (
		<div>
			<Head>
				<title>Cinemas</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<LogoBar />
			<NavMenu />
			<main className={styles.container}>
				<div className={styles.content}>
					<div className={styles.box}>
						<h2>Coming Soon</h2>
					</div>
				</div>
			</main>
		</div>
	);
}
