import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { useSelector } from "react-redux";
import styles from "../styles/Home.module.scss";
import Head from "next/head";
import LogoBar from "../src/components/LogoBar";
import NavMenu from "../src/components/NavMenu";
import Modal from "../src/components/Modal";
import Carousel from "../src/components/Carousel";
import ShowtimeContainer from "../src/containers/ShowtimesContainer";

export default function Home() {
	const [isBrowser, setIsBrowser] = useState(false); // required to access document
	const modalState = useSelector((state) => state.modal); // redux modalState

	useEffect(() => {
		setIsBrowser(true); // set to true when document is loaded/accessible
	}, []);

	// Disable background scroll when modal is visible
	if (isBrowser && modalState.isVisible) {
		const body = document.querySelector("body");
		body.style.overflow = "hidden";
	}

	// Reset disabled background scroll behavior
	if (isBrowser && !modalState.isVisible) {
		const body = document.querySelector("body");
		body.style.overflow = "";
	}

	const trailerModal =
		isBrowser && modalState.type === "view-trailer"
			? createPortal(
					<Modal header={`${modalState.info.title} - Trailer`} color="#007DD8">
						<iframe
							width="100%"
							height="400px"
							frameBorder="0"
							border="0"
							cellSpacing="0"
							src={`${modalState.info.trailerLink}?autoplay=1`}
						></iframe>
					</Modal>,
					document.getElementById("modal-root")
			  )
			: null;

	const previewSeatsModal = isBrowser
		? createPortal(
				<Modal header="Preview Seats" color="#007DD8">
					<p>
						Hello this is going to be a test to see how the content part of the
						modal adjusts to more content and to varying sizes
					</p>
				</Modal>,
				document.getElementById("modal-root")
		  )
		: null;

	console.log(modalState);
	return (
		<div>
			<Head>
				<title>Cinemas</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* View Trailer Modal */}
			{isBrowser &&
				modalState.isVisible &&
				modalState.type === "view-trailer" &&
				trailerModal}

			{/* Preview Seats Modal */}
			{isBrowser &&
				modalState.isVisible &&
				modalState.type === "preview-seats" &&
				previewSeatsModal}

			<main className={styles.container}>
				<LogoBar />
				<NavMenu />
				<Carousel />
				<ShowtimeContainer />
			</main>

			{/* <footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer> */}
		</div>
	);
}
